name: build
on:
  push:
  pull_request:

jobs:
  build:
    name: Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: node environment
        run: |
          node -v
          npm -v
      - run: npm install
      - run: npm test
      - name: Coveralls
        if: matrix.node == 14
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
